# Generated by Django 3.1.3 on 2020-11-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=20)),
                ('transmission', models.CharField(choices=[('A', 'Automatico'), ('M', 'Manual')], max_length=1)),
                ('year', models.PositiveIntegerField(blank=True)),
                ('brand', models.CharField(max_length=20)),
            ],
        ),
    ]
