# Generated by Django 3.1.3 on 2020-11-06 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='model',
            new_name='car_model',
        ),
    ]
