# Generated by Django 3.1.3 on 2020-11-10 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_car_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='day',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes')], max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='schedule',
            field=models.CharField(choices=[('8:00 am', '8:00 am'), ('9:00 am', '9:00 am'), ('10:00 am', '10:00 am'), ('11:00 am', '11:00 am'), ('1:00 am', '1:00 pm'), ('2:00 am', '2:00 pm'), ('3:00 am', '3:00 pm'), ('4:00 am', '4:00 pm')], max_length=10),
        ),
    ]
