# Generated by Django 3.1.3 on 2020-11-13 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_auto_20201113_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
