# Generated by Django 3.1.3 on 2020-11-13 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_auto_20201113_0516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='day',
        ),
    ]
